{
 "title": "Kubernetes Audit Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "SecretsUnAuthenticated",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({filename=\"/etc/kubernetes/audit/audit.log\"}|json|annotations_authorization_k8s_io_decision=\"forbid\"|=\"/api/v1/namespaces/kube-system/secrets\"[5m]))",
     "legendFormat": "secrets-unauthenticated"
    }
   ]
  },
  {
   "title": "ConfigmapUnAuthenticated",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({filename=\"/etc/kubernetes/audit/audit.log\"}|json|annotations_authorization_k8s_io_decision=\"forbid\"|=\"/api/v1/namespaces/kube-system/configmap\"[5m]))",
     "legendFormat": "configmap-unauthenticated"
    }
   ]
  },
  {
   "title": "APIServerActivities",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{filename=\"/etc/kubernetes/audit/audit.log\"} | json | line_format \"request for {{.requestURI}} with HTTP status: {{.responseStatus_code}} \""
    }
   ]
  }
 ]
}